disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - force_unwrapping
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - last_where

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

included:
  - MeetNotes

excluded:
  - DerivedData
  - .build
  - Packages

reporter: "xcode"
